version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vigilia
      POSTGRES_PASSWORD: vigilia
      POSTGRES_DB: vigilia
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vigilia"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: hackathon-secret-change-in-prod
      DB_NAME: vigilia
      DB_USER: vigilia
      DB_PASSWORD: vigilia
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "True"
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "until python manage.py migrate --noinput; do echo 'DB not ready, retrying...'; sleep 3; done &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pg_data:
